# CMake generated Testfile for 
# Source directory: E:/mongo-c-dirver_VS2019
# Build directory: E:/mongo-c-dirver_VS2019/build_vs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("E:/mongo-c-dirver_VS2019/build_vs/LoadTests-Debug.cmake")
include("E:/mongo-c-dirver_VS2019/build_vs/LoadTests-Release.cmake")
include("E:/mongo-c-dirver_VS2019/build_vs/LoadTests-MinSizeRel.cmake")
include("E:/mongo-c-dirver_VS2019/build_vs/LoadTests-RelWithDebInfo.cmake")
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(mongoc/fixtures/fake_imds/start "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/proc-ctl.py" "start" "--ctl-dir=E:/mongo-c-dirver_VS2019/build_vs/.ctl" "--cwd=E:/mongo-c-dirver_VS2019/build_vs" "--spawn-wait=0.2" "--" "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/bottle.py" "fake_kms_provider_server:kms_provider" "--bind" "localhost:14987")
  set_tests_properties(mongoc/fixtures/fake_imds/start PROPERTIES  FIXTURES_SETUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;29;add_test;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;0;;E:/mongo-c-dirver_VS2019/CMakeLists.txt;371;include;E:/mongo-c-dirver_VS2019/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(mongoc/fixtures/fake_imds/start "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/proc-ctl.py" "start" "--ctl-dir=E:/mongo-c-dirver_VS2019/build_vs/.ctl" "--cwd=E:/mongo-c-dirver_VS2019/build_vs" "--spawn-wait=0.2" "--" "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/bottle.py" "fake_kms_provider_server:kms_provider" "--bind" "localhost:14987")
  set_tests_properties(mongoc/fixtures/fake_imds/start PROPERTIES  FIXTURES_SETUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;29;add_test;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;0;;E:/mongo-c-dirver_VS2019/CMakeLists.txt;371;include;E:/mongo-c-dirver_VS2019/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(mongoc/fixtures/fake_imds/start "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/proc-ctl.py" "start" "--ctl-dir=E:/mongo-c-dirver_VS2019/build_vs/.ctl" "--cwd=E:/mongo-c-dirver_VS2019/build_vs" "--spawn-wait=0.2" "--" "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/bottle.py" "fake_kms_provider_server:kms_provider" "--bind" "localhost:14987")
  set_tests_properties(mongoc/fixtures/fake_imds/start PROPERTIES  FIXTURES_SETUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;29;add_test;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;0;;E:/mongo-c-dirver_VS2019/CMakeLists.txt;371;include;E:/mongo-c-dirver_VS2019/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(mongoc/fixtures/fake_imds/start "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/proc-ctl.py" "start" "--ctl-dir=E:/mongo-c-dirver_VS2019/build_vs/.ctl" "--cwd=E:/mongo-c-dirver_VS2019/build_vs" "--spawn-wait=0.2" "--" "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/bottle.py" "fake_kms_provider_server:kms_provider" "--bind" "localhost:14987")
  set_tests_properties(mongoc/fixtures/fake_imds/start PROPERTIES  FIXTURES_SETUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;29;add_test;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;0;;E:/mongo-c-dirver_VS2019/CMakeLists.txt;371;include;E:/mongo-c-dirver_VS2019/CMakeLists.txt;0;")
else()
  add_test(mongoc/fixtures/fake_imds/start NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(mongoc/fixtures/fake_imds/stop "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/proc-ctl.py" "stop" "--ctl-dir=E:/mongo-c-dirver_VS2019/build_vs/.ctl" "--if-not-running=ignore")
  set_tests_properties(mongoc/fixtures/fake_imds/stop PROPERTIES  FIXTURES_CLEANUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;35;add_test;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;0;;E:/mongo-c-dirver_VS2019/CMakeLists.txt;371;include;E:/mongo-c-dirver_VS2019/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(mongoc/fixtures/fake_imds/stop "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/proc-ctl.py" "stop" "--ctl-dir=E:/mongo-c-dirver_VS2019/build_vs/.ctl" "--if-not-running=ignore")
  set_tests_properties(mongoc/fixtures/fake_imds/stop PROPERTIES  FIXTURES_CLEANUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;35;add_test;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;0;;E:/mongo-c-dirver_VS2019/CMakeLists.txt;371;include;E:/mongo-c-dirver_VS2019/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(mongoc/fixtures/fake_imds/stop "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/proc-ctl.py" "stop" "--ctl-dir=E:/mongo-c-dirver_VS2019/build_vs/.ctl" "--if-not-running=ignore")
  set_tests_properties(mongoc/fixtures/fake_imds/stop PROPERTIES  FIXTURES_CLEANUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;35;add_test;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;0;;E:/mongo-c-dirver_VS2019/CMakeLists.txt;371;include;E:/mongo-c-dirver_VS2019/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(mongoc/fixtures/fake_imds/stop "D:/Python312/python.exe" "-u" "--" "E:/mongo-c-dirver_VS2019/build/proc-ctl.py" "stop" "--ctl-dir=E:/mongo-c-dirver_VS2019/build_vs/.ctl" "--if-not-running=ignore")
  set_tests_properties(mongoc/fixtures/fake_imds/stop PROPERTIES  FIXTURES_CLEANUP "mongoc/fixtures/fake_imds" _BACKTRACE_TRIPLES "E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;35;add_test;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;42;mongo_define_subprocess_fixture;E:/mongo-c-dirver_VS2019/build/cmake/TestFixtures.cmake;0;;E:/mongo-c-dirver_VS2019/CMakeLists.txt;371;include;E:/mongo-c-dirver_VS2019/CMakeLists.txt;0;")
else()
  add_test(mongoc/fixtures/fake_imds/stop NOT_AVAILABLE)
endif()
subdirs("src/common")
subdirs("src/libbson")
subdirs("src/libmongoc")
subdirs("src")
