
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2024/8/14 14:59:30。
      节点 1 上的项目“E:\\mongo-c-dirver_VS2019\\build_vs\\CMakeFiles\\CheckCXX\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        d:\\Microsoft Visual Studio 16.0\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        d:\\Microsoft Visual Studio 16.0\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\mongo-c-dirver_VS2019\\build_vs\\CMakeFiles\\CheckCXX\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=d:\\Microsoft Visual Studio 16.0\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\mongo-c-dirver_VS2019\\build_vs\\CMakeFiles\\CheckCXX\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.72
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/mongo-c-dirver_VS2019/build_vs/CMakeFiles/CheckCXX/CMakeFiles/3.30.2/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "D:/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/mongo-c-dirver_VS2019/build_vs/CMakeFiles/CheckCXX/CMakeFiles/CMakeScratch/TryCompile-d39nty"
      binary: "E:/mongo-c-dirver_VS2019/build_vs/CMakeFiles/CheckCXX/CMakeFiles/CMakeScratch/TryCompile-d39nty"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "E:/mongo-c-dirver_VS2019/build/cmake"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/mongo-c-dirver_VS2019/build_vs/CMakeFiles/CheckCXX/CMakeFiles/CMakeScratch/TryCompile-d39nty'
        
        Run Build Command(s): "d:/Microsoft Visual Studio 16.0/MSBuild/Current/Bin/MSBuild.exe" cmTC_5d807.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2024/8/14 14:59:31。
        节点 1 上的项目“E:\\mongo-c-dirver_VS2019\\build_vs\\CMakeFiles\\CheckCXX\\CMakeFiles\\CMakeScratch\\TryCompile-d39nty\\cmTC_5d807.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_5d807.dir\\Debug\\”。
          正在创建目录“E:\\mongo-c-dirver_VS2019\\build_vs\\CMakeFiles\\CheckCXX\\CMakeFiles\\CMakeScratch\\TryCompile-d39nty\\Debug\\”。
          正在创建目录“cmTC_5d807.dir\\Debug\\cmTC_5d807.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_5d807.dir\\Debug\\cmTC_5d807.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          d:\\Microsoft Visual Studio 16.0\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5d807.dir\\Debug\\\\" /Fd"cmTC_5d807.dir\\Debug\\vc142.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\CMake\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30154 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5d807.dir\\Debug\\\\" /Fd"cmTC_5d807.dir\\Debug\\vc142.pdb" /external:W1 /Gd /TP /errorReport:queue "D:\\CMake\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          d:\\Microsoft Visual Studio 16.0\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\mongo-c-dirver_VS2019\\build_vs\\CMakeFiles\\CheckCXX\\CMakeFiles\\CMakeScratch\\TryCompile-d39nty\\Debug\\cmTC_5d807.exe" /INCREMENTAL /ILK:"cmTC_5d807.dir\\Debug\\cmTC_5d807.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/mongo-c-dirver_VS2019/build_vs/CMakeFiles/CheckCXX/CMakeFiles/CMakeScratch/TryCompile-d39nty/Debug/cmTC_5d807.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/mongo-c-dirver_VS2019/build_vs/CMakeFiles/CheckCXX/CMakeFiles/CMakeScratch/TryCompile-d39nty/Debug/cmTC_5d807.lib" /MACHINE:X64  /machine:x64 cmTC_5d807.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_5d807.vcxproj -> E:\\mongo-c-dirver_VS2019\\build_vs\\CMakeFiles\\CheckCXX\\CMakeFiles\\CMakeScratch\\TryCompile-d39nty\\Debug\\cmTC_5d807.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_5d807.dir\\Debug\\cmTC_5d807.tlog\\unsuccessfulbuild”。
          正在对“cmTC_5d807.dir\\Debug\\cmTC_5d807.tlog\\cmTC_5d807.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\mongo-c-dirver_VS2019\\build_vs\\CMakeFiles\\CheckCXX\\CMakeFiles\\CMakeScratch\\TryCompile-d39nty\\cmTC_5d807.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.54
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "D:/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': d:/Microsoft Visual Studio 16.0/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.30/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "D:/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "D:/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Running the CXX compiler's linker: "d:/Microsoft Visual Studio 16.0/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.29.30154.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
